/*!
 * 
 *   mouse-to-pos v0.0.1
 *   git remote add origin https://github.com/leoxanigm/MouseToPos.git
 *
 *   Copyright (c) Zola (https://zola.dev) and project contributors.
 *
 *   This source code is licensed under the MIT license found in the
 *   LICENSE file in the root directory of this source tree.
 *
 */
!function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():"function"==typeof define&&define.amd?define([],e):"object"==typeof exports?exports.MouseToPos=e():t.MouseToPos=e()}(self,(()=>(()=>{"use strict";var t={d:(e,i)=>{for(var o in i)t.o(i,o)&&!t.o(e,o)&&Object.defineProperty(e,o,{enumerable:!0,get:i[o]})},o:(t,e)=>Object.prototype.hasOwnProperty.call(t,e)},e={};t.d(e,{default:()=>v});var i,o,s,n,r,a,h,f,c,d,l,w,p=function(t,e,i,o,s){if("m"===o)throw new TypeError("Private method is not writable");if("a"===o&&!s)throw new TypeError("Private accessor was defined without a setter");if("function"==typeof e?t!==e||!s:!e.has(t))throw new TypeError("Cannot write private member to an object whose class did not declare it");return"a"===o?s.call(t,i):s?s.value=i:e.set(t,i),i},u=function(t,e,i,o){if("a"===i&&!o)throw new TypeError("Private accessor was defined without a getter");if("function"==typeof e?t!==e||!o:!e.has(t))throw new TypeError("Cannot read private member from an object whose class did not declare it");return"m"===i?o:"a"===i?o.call(t):o?o.value:e.get(t)};o=new WeakMap,s=new WeakMap,n=new WeakMap,r=new WeakMap,a=new WeakMap,h=new WeakMap,f=new WeakMap,c=new WeakMap,d=new WeakMap,w=new WeakMap,i=new WeakSet,l=function(){if(void 0===u(this,s,"f")||!Array.isArray(u(this,s,"f")))throw new TypeError("You must provide an event list with at least one event.");if(!(u(this,o,"f")instanceof HTMLElement))throw new TypeError("You must provide a container element.");u(this,s,"f").forEach((t=>{const e=u(this,a,"f")[t];u(this,o,"f").addEventListener(e,(e=>{u(this,w,"f").call(this,e,u(this,o,"f"),t)}))}))};const v=class{constructor(t){var e,v;i.add(this),o.set(this,void 0),s.set(this,void 0),n.set(this,void 0),r.set(this,void 0),a.set(this,{hover:"mousemove",click:"mousedown"}),h.set(this,void 0),f.set(this,void 0),c.set(this,void 0),d.set(this,void 0),w.set(this,((t,e,i)=>{t.stopPropagation();const{x:o,y:s,width:n,height:r}=this.getXY(t,e);u(this,f,"f")?u(this,h,"f").call(this,o,s,i):o===u(this,c,"f")&&s===u(this,d,"f")&&"click"!==i||(u(this,h,"f").call(this,o,s,i),p(this,c,o,"f"),p(this,d,s,"f"))})),this.getXY=(t,e)=>{const{clientX:i,clientY:o}=t;let{top:s,left:a,width:h,height:f}=e.getBoundingClientRect();const c=h/u(this,r,"f"),d=f/u(this,n,"f");return{x:Math.floor((i-a)/c)*c,y:Math.floor((o-s)/d)*d,width:c,height:d}},p(this,o,t.container,"f"),p(this,s,t.events,"f"),p(this,h,t.outputFunction,"f"),p(this,n,(null===(e=t.subdivision)||void 0===e?void 0:e.rows)||1,"f"),p(this,r,(null===(v=t.subdivision)||void 0===v?void 0:v.cols)||1,"f"),p(this,f,t.greedy||!1,"f"),u(this,i,"m",l).call(this)}};return e=e.default})()));